name: wildtails_ghana
description: WildTails Ghana - Wildlife Conservation & Ecotourism App
publish_to: 'none'
version: 1.0.0+4

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  provider: ^6.1.1
  go_router: ^13.0.0
  shared_preferences: ^2.2.2
  flutter_animate: ^4.5.0
  cached_network_image: ^3.3.1
  flutter_map: ^6.1.0
  latlong2: ^0.9.0
  url_launcher: ^6.2.4
  image_picker: ^1.0.7
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
